# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Multipay_Networking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multipay_Networking

	pod 'Alamofire', '~> 5.1'

  target 'Multipay_NetworkingTests' do
    # Pods for testing
  end

end

target 'Multipay_NetworkingPackageDescription' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multipay_NetworkingPackageDescription

end
